# Metadata syntax: <https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions>

name: WIP
description: WIP

inputs:
  strip-version-prefix:
    description: Strip the "v" prefix (v1.2.3 to 1.2.3), "true" or "false"
    required: false
    default: 'false'

outputs:
  version:
    description: Version (v1.2.3 for example) value
  version-slug:
    description: Version (v1-2-3 for example) value

runs:
  using: node12
  main: dist/index.js
