# Metadata syntax: <https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions>

name: WIP
description: WIP

outputs:
  is-branch:
    description: Workflow was triggered on a branch ("true" or "false")
  is-tag:
    description: Workflow was triggered on a tag ("true" or "false")
  branch-name:
    description: Current branch name ("feature/Fix-Something" for example; only for runs on a branches)
  branch-name-slug:
    description: Slugged version of "branch-name" ("feature-fix-something" for example; only for runs on a branches)
  tag-name:
    description: Tag name ("Any-Tag" or "v1.2.3" for example; only for runs on a tags)
  tag-name-slug:
    description: Slugged version of "tag-name" ("any-tag" or "v1.2.3" for example; only for runs on a tags)
  version:
    description: Version value ("v1.2.3-RC1" for example). Available only for tags in semver format
  version-slug:
    description: Slugged version of "version" ("v1.2.3-RC1" for example). Available only for tags in semver format

runs:
  using: node12
  main: dist/index.js
