name: del

on: [delete]

jobs:
  clean:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v3

      - name: Run this action
        uses: ./
        id: slug
        with:
          to-slug: ${{ github.event.ref }}
