name: TEST_ISSUE

on:
  pull_request:
    types:
      - closed

jobs:
  run-this-action:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run this action
        uses: ./
